### ISSUE TITLE
Error: Connection got disposed

### ISSUE THREAD

**Issue by shulhi** [reasonml-editor/vscode-reasonml#142]
I have reformat on save set, and whenever I saved a file I get the following error:

```
[Error - 10:07:00 PM] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/home/shulhi/.vscode/extensions/freebroccolo.reasonml-1.0.14/node_modules/vscode-jsonrpc/lib/events.js:135:36)
```

I am using version 1.0.14

**Comment by freebroccolo** [comment]
Can you provide me with the following information?

- OS
- How you have your tools installed (e.g., `opam`, `reason-cli`, etc.)
- How you are launching the editor

If you are on Linux and using `opam`, you will need to ensure that the Opam environment is initialized before you start the editor. This may require launching `code` from a terminal.

**Comment by nerdyworm** [comment]
I'm also getting this error.

- OSX 10.12.16
- Installed via `npm install -g https://github.com/reasonml/reason-cli/archive/3.0.1-bin-darwin.tar.gz`
- opam is not installed
- `$ code .`

This only seems to happen when saving `.ml` files.  `.re` files do not seem to trigger formatting.

If there is anything else I can provide to help you help us please let me know :)

**Comment by freebroccolo** [comment]
Formatting on save for OCaml requires having `ocp-indent` installed (usually via opam). That may be why you are seeing this error. I'm working on providing some better feedback about this in upcoming versions.

**Comment by nerdyworm** [comment]
Installing ocaml and opam via homebrew seemed to get everything squared away.

`brew install ocaml opam` - also had to force link to overwrite the npm install
`opam install ocp-indent`
`opam install merlin` 

Thanks for pointing me in the right direction!

**Comment by luisliuchao** [comment]
`yarn global add reason-cli` or `npm install -g reason-cli`

It will install all missing packages needed for VSC extension
